# Generated by Django 2.1.5 on 2019-02-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0003_auto_20190206_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalshirt',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
